name = input("Enter your name:")
city = input("Enter your ciyt:")
fav_food = input("Enter your fav food:")
fav_animal = input("Enter your fav animal:")
fav_hobbies = input("Enter your fav hobbies:")
fav_flim = input("Enter your fav flim:")
fav_bike = input("Enter your fav bike:")
fav_car = input("Enter your fav car:")
fav_game = input("Enter your fav game:")
fav_song= input("Enter your fav song:")


print("!!!!JAANKARI!!!!")
print(f'{name=}')
print(f'{city=}')
print(f'{fav_food=}')
print(f'{fav_animal=}')
print(f'{fav_hobbies=}')
print(f'{fav_flim=}')
print(f'{fav_bike=}')
print(f'{fav_car=}')
print(f'{fav_game=}')
print(f'{fav_song=}')